const KEY="exam_v1";
const seed={user:null,exams:[
{id:"ENG-001",title:"Production Engineering Basics",category:"Engineering",duration:10,pass:60,questions:[
{text:"What does MTBF measure?",options:["Repair duration","Average time between failures","Production quantity","Inspection time"],answer:1,points:10},
{text:"What does MTTR primarily measure?",options:["Mean time to repair","Mean time to failure","Yield","Cycle time"],answer:0,points:10},
{text:"Which chart monitors count of defects per unit?",options:["X̄-R","C chart","Histogram","Pareto"],answer:1,points:10},
{text:"What is a bottleneck?",options:["Fastest process","Process limiting system output","Inspection station","Storage area"],answer:1,points:10},
{text:"COPQ means:",options:["Cost of Production Quality","Cost of Poor Quality","Control of Process Quality","Cost per Output Quantity"],answer:1,points:10},
{text:"What is yield?",options:["Good output relative to input","Downtime only","Defect count","Labor hours"],answer:0,points:10}
]},
{id:"SAFE-001",title:"Factory Safety Assessment",category:"Safety",duration:8,pass:70,questions:[
{text:"What should you do first after a chemical splash in the eye?",options:["Rub the eye","Flush immediately with clean water","Wait for a supervisor","Close the eye"],answer:1,points:10},
{text:"PPE stands for:",options:["Personal Protective Equipment","Production Process Evaluation","Plant Protection Engineering","Personal Process Entry"],answer:0,points:10},
{text:"Emergency exits should be:",options:["Locked","Obstructed","Clearly accessible","Used for storage"],answer:2,points:10},
{text:"A near miss should be:",options:["Ignored","Reported and analyzed","Deleted","Hidden"],answer:1,points:10}
]}
],attempts:[]};
function load(){try{return JSON.parse(localStorage.getItem(KEY))||seed}catch{return seed}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
let state=load(), timer=null;
const app=document.getElementById("app");
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function top(){return '<header class="topbar"><div class="brand">EXAM<span>.</span></div><div class="muted">'+(state.user?esc(state.user.name):"Assessment Platform")+'</div></header>'}
function login(){app.innerHTML='<div class="shell"><div class="login card"><div class="brand">EXAM<span>.</span></div><h1>Student Assessment</h1><p class="muted">Enter your name to start.</p><div class="field"><label>Student name</label><input id="name" placeholder="e.g. Ahmed Mohamed"></div><button class="btn primary" style="width:100%" onclick="startStudent()">Continue</button><p class="muted" style="font-size:12px;margin-top:18px">Demo MVP — data is stored locally in this browser.</p></div></div>'}
function startStudent(){const n=document.getElementById("name").value.trim();if(!n)return alert("Enter your name.");state.user={name:n,role:"student"};save();studentHome()}
function studentHome(){app.innerHTML=top()+'<main class="container"><div class="hero"><div><div class="eyebrow">Student portal</div><div class="h1">Choose an assessment</div><div class="muted">Select an exam and complete it before the timer expires.</div></div><button class="btn ghost" onclick="admin()">Admin view</button></div><div class="grid">'+state.exams.map(e=>'<div class="card"><div class="eyebrow">'+esc(e.category)+'</div><h2>'+esc(e.title)+'</h2><p class="muted">'+e.questions.length+' questions · '+e.duration+' min · Pass '+e.pass+'%</p><button class="btn primary" onclick="beginExam(\''+e.id+'\')">Start exam</button></div>').join("")+'</div></main>'}
function beginExam(id){const e=state.exams.find(x=>x.id===id);let answers=Array(e.questions.length).fill(null),left=e.duration*60,index=0;function render(){const q=e.questions[index];app.innerHTML=top()+'<main class="container"><div class="exam-head"><div><div class="eyebrow">'+esc(e.category)+'</div><h1>'+esc(e.title)+'</h1><div class="progress"><div style="width:'+((index+1)/e.questions.length*100)+'%"></div></div></div><div class="timer" id="timer"></div></div><div class="card"><div class="qnum">Question '+(index+1)+' of '+e.questions.length+'</div><h2>'+esc(q.text)+'</h2>'+q.options.map((o,i)=>'<label class="option '+(answers[index]===i?'selected':'')+'"><input type="radio" name="opt" '+(answers[index]===i?'checked':'')+' onchange="window._ans='+i+'"> <span>'+esc(o)+'</span></label>').join("")+'</div><div class="row" style="margin-top:18px"><button class="btn ghost" onclick="prev()" '+(index===0?'disabled':'')+'>Previous</button><button class="btn primary" onclick="next()">'+(index===e.questions.length-1?'Submit':'Next')+'</button></div></main>';window._ans=answers[index];window.prev=()=>{answers[index]=window._ans;index--;render()};window.next=()=>{answers[index]=window._ans;if(index===e.questions.length-1){finish()}else{index++;render()}};if(!timer)timer=setInterval(()=>{left--;const el=document.getElementById("timer");if(el)el.textContent=Math.floor(left/60)+":"+String(left%60).padStart(2,"0");if(left<=0){clearInterval(timer);timer=null;finish()}},1000);const el=document.getElementById("timer");if(el)el.textContent=Math.floor(left/60)+":"+String(left%60).padStart(2,"0")}function finish(){clearInterval(timer);timer=null;const e=state.exams.find(x=>x.id===id);const answers=window._answers||[];let score=0;e.questions.forEach((q,i)=>{if(answers[i]===q.answer)score+=q.points});const total=e.questions.reduce((a,q)=>a+q.points,0);const pct=Math.round(score/total*100);state.attempts.push({id:Date.now(),student:state.user.name,exam:e.title,score,total,pct,passed:pct>=e.pass,date:new Date().toISOString()});save();app.innerHTML=top()+'<main class="container"><div class="card result"><div class="eyebrow">Assessment complete</div><h1>'+esc(e.title)+'</h1><div class="score">'+pct+'%</div><h2 class="'+(pct>=e.pass?'pass':'fail')+'" style="display:inline-block;padding:8px 14px;border-radius:999px">'+(pct>=e.pass?'PASSED':'NOT PASSED')+'</h2><p class="muted">Score: '+score+' / '+total+'</p><button class="btn primary" onclick="studentHome()">Back to exams</button></div></main>'}
function admin(){state.user={name:"Administrator",role:"admin"};save();adminHome()}
function adminHome(){const total=state.attempts.length,avg=total?Math.round(state.attempts.reduce((a,x)=>a+x.pct,0)/total):0,pass=total?Math.round(state.attempts.filter(x=>x.passed).length/total*100):0;app.innerHTML=top()+'<main class="container"><div class="hero"><div><div class="eyebrow">Administration</div><div class="h1">Assessment dashboard</div><div class="muted">Manage exams and monitor student performance.</div></div><button class="btn ghost" onclick="studentHome()">Student view</button></div><div class="grid" style="margin-bottom:22px"><div class="card"><div class="muted">Exams</div><div class="stat">'+state.exams.length+'</div></div><div class="card"><div class="muted">Attempts</div><div class="stat">'+total+'</div></div><div class="card"><div class="muted">Average score</div><div class="stat">'+avg+'%</div></div><div class="card"><div class="muted">Pass rate</div><div class="stat">'+pass+'%</div></div></div><div class="card"><div class="row"><h2>Recent attempts</h2><button class="btn danger" onclick="resetData()">Reset demo data</button></div>'+(total?'<table class="table"><thead><tr><th>Student</th><th>Exam</th><th>Score</th><th>Status</th><th>Date</th></tr></thead><tbody>'+state.attempts.slice().reverse().map(a=>'<tr><td>'+esc(a.student)+'</td><td>'+esc(a.exam)+'</td><td>'+a.pct+'%</td><td><span class="badge '+(a.passed?'pass':'fail')+'">'+(a.passed?'PASS':'FAIL')+'</span></td><td>'+new Date(a.date).toLocaleString()+'</td></tr>').join("")+'</tbody></table>':'<p class="muted">No attempts yet.</p>')+'</div></main>'}
function resetData(){if(confirm("Reset all local demo attempts?")){state.attempts=[];save();adminHome()}}
window.onload=login;
