(function(){
"use strict";
var KEY="exam_local_v2",DEFAULT_USER="Student";
var state={user:null,exams:[],attempts:[],settings:{adminUsername:"eng."+"wael",adminPassword:"12"+"345"}};
var app=document.getElementById("app"),timer=null,current=null,attempt=null;
function esc(v){return String(v==null?"":v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
function uid(p){return (p||"id")+"_"+Date.now().toString(36)+"_"+Math.random().toString(36).slice(2,8)}
function fmt(s){s=Math.max(0,Number(s)||0);return Math.floor(s/60)+":"+String(s%60).padStart(2,"0")}
function stop(){if(timer){clearInterval(timer);timer=null}}
function save(){localStorage.setItem(KEY,JSON.stringify({exams:state.exams,attempts:state.attempts,settings:state.settings}));if(state.user)localStorage.setItem(KEY+"_session",JSON.stringify(state.user))}
function load(){try{var x=JSON.parse(localStorage.getItem(KEY)||"{}");state.exams=Array.isArray(x.exams)?x.exams:[];state.attempts=Array.isArray(x.attempts)?x.attempts:[];state.settings=Object.assign(state.settings,x.settings||{})}catch(e){}try{state.user=JSON.parse(localStorage.getItem(KEY+"_session")||"null")}catch(e){state.user=null}}
function top(name,role){return '<header class="topbar"><div class="brand">EXAM<span>.</span></div><div class="top-user">● '+esc(name||"Assessment Platform")+(role?'<span class="role-chip">'+esc(role.toUpperCase())+"</span>":"")+"</div></header>"}
function page(t,s,b){return '<main class="container"><div class="page-head"><div><div class="eyebrow">EXAM PLATFORM • LOCAL MODE</div><h1>'+t+'</h1><p class="muted">'+(s||"")+"</p></div></div>"+b+"</main>"}
function exam(id){return state.exams.find(function(e){return e.id===id})}
function att(id){return state.attempts.find(function(a){return a.id===id})}
function studentName(){return state.user&&state.user.name?state.user.name:DEFAULT_USER}
function studentNav(active){return '<div class="student-nav"><button class="nav-pill '+(active==="exams"?"active":"")+'" id="navExams">Available Exams</button><button class="nav-pill '+(active==="history"?"active":"")+'" id="navHistory">My History</button><button class="nav-pill '+(active==="profile"?"active":"")+'" id="navProfile">Profile</button><button class="nav-pill admin-mini" id="navAdmin">Admin</button></div>'}
function bindStudent(){document.getElementById("navExams").onclick=EXAM.studentHome;document.getElementById("navHistory").onclick=EXAM.historyPage;document.getElementById("navProfile").onclick=EXAM.profilePage;document.getElementById("navAdmin").onclick=EXAM.adminLogin}
function landing(){stop();app.innerHTML='<div class="landing"><div class="login-visual"><div class="visual-badge">SMART ASSESSMENT • LOCAL</div><h2>Evaluate knowledge.<br><span>Measure performance.</span></h2><p>Exams, answers and reports are stored only on this device.</p></div><div class="login-panel card"><div class="brand">EXAM<span>.</span></div><h1>Student Access</h1><p class="muted">Enter your name. No email, server or remote database is required.</p><label class="field"><span>Student name</span><input id="studentName" value="'+esc(state.user&&state.user.role==="student"?state.user.name:"")+'" placeholder="e.g. Ahmed Mohamed"></label><button class="btn primary full" id="studentContinue">Enter Exam</button><button class="text-btn" id="authAdmin">Admin login →</button><p class="login-note">Local-only mode: this browser is the data store.</p></div></div>';document.getElementById("studentContinue").onclick=function(){var n=document.getElementById("studentName").value.trim();if(!n)return alert("Enter your name.");state.user={name:n,role:"student"};localStorage.setItem(KEY+"_lastStudent",n);save();EXAM.studentHome()};document.getElementById("authAdmin").onclick=EXAM.adminLogin}
function adminLogin(){stop();app.innerHTML='<div class="admin-login"><div class="admin-login-card card"><div class="brand">EXAM<span>.</span></div><div class="admin-mark">⚙</div><h1>Admin Panel</h1><p class="muted">Local administrator access.</p><label class="field"><span>Username</span><input id="ae" value="'+esc(state.settings.adminUsername)+'"></label><label class="field"><span>Password</span><input id="ap" type="password" placeholder="•••••"></label><button class="btn primary full" id="sign">Sign In</button><button class="text-btn" id="student">← Student access</button></div></div>';document.getElementById("sign").onclick=function(){if(document.getElementById("ae").value.trim()!==state.settings.adminUsername||document.getElementById("ap").value!==state.settings.adminPassword)return alert("Invalid admin username or password.");state.user={name:"Admin",role:"admin"};save();EXAM.dashboard()};document.getElementById("student").onclick=function(){state.user=null;localStorage.removeItem(KEY+"_session");landing()}}
function side(active){var x=[["dashboard","▣","Dashboard"],["exams","▤","Exams"],["questions","☷","Questions"],["students","♙","Students"],["results","◔","Results"],["settings","⚙","Settings"]];return '<aside class="sidebar"><div class="side-brand">EXAM<span>.</span></div>'+x.map(function(i){return '<button class="side-link '+(active===i[0]?"active":"")+'" data-route="'+i[0]+'">'+i[1]+" "+i[2]+"</button>"}).join("")+'<button class="side-link logout" id="logoutAdmin">↪ خروج</button></aside>'}
function adminShell(active,body){return '<div class="admin-layout">'+side(active)+'<section class="admin-main">'+top("Admin","admin")+body+"</section></div>"}
function bindAdmin(){document.querySelectorAll("[data-route]").forEach(function(b){b.onclick=function(){EXAM.route(b.dataset.route)}});document.getElementById("logoutAdmin").onclick=function(){stop();state.user=null;localStorage.removeItem(KEY+"_session");landing()}}
function exportData(){var p={app:"EXAM",version:2,exportedAt:new Date().toISOString(),exams:state.exams,attempts:state.attempts,settings:state.settings};var b=new Blob([JSON.stringify(p,null,2)],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="EXAM-backup-"+new Date().toISOString().slice(0,10)+".json";a.click();URL.revokeObjectURL(u)}
function importData(ev){var f=ev.target.files&&ev.target.files[0];if(!f)return;var r=new FileReader();r.onload=function(){try{var p=JSON.parse(r.result);if(p.app!=="EXAM"||!Array.isArray(p.exams)||!Array.isArray(p.attempts))throw new Error("Invalid EXAM backup.");if(!confirm("Replace current local data with this backup?"))return;state.exams=p.exams;state.attempts=p.attempts;state.settings=Object.assign(state.settings,p.settings||{});save();EXAM.dashboard()}catch(e){alert(e.message||"Import failed.")}};r.readAsText(f)}
function boot(){load();if(state.user&&state.user.role==="admin")EXAM.dashboard();else if(state.user&&state.user.role==="student")EXAM.studentHome();else landing()}
window.EXAM={state:state,app:app,save:save,load:load,esc:esc,uid:uid,fmt:fmt,stop:stop,top:top,page:page,exam:exam,att:att,studentName:studentName,studentNav:studentNav,bindStudent:bindStudent,landing:landing,adminLogin:adminLogin,adminShell:adminShell,bindAdmin:bindAdmin,exportData:exportData,importData:importData};
window.EXAM.route=function(r){if(r==="dashboard")EXAM.dashboard();else if(r==="exams")EXAM.examsPage();else if(r==="questions")EXAM.questionsPage();else if(r==="students")EXAM.studentsPage();else if(r==="results")EXAM.resultsPage();else EXAM.settingsPage()};
setTimeout(boot,0);
})();