(function(){
"use strict";
var E=window.EXAM,S=E.state,app=E.app,current=null,attempt=null,timer=null;
function icon(c){return c==="Safety"?"⚠":c==="Quality"?"✓":c==="Maintenance"?"⚙":"◉"}
function start(id){current=E.exam(id);if(!current||!current.questions.length)return alert("This exam has no questions.");attempt={answers:Array(current.questions.length).fill(null),index:0,left:current.duration*60,started:Date.now()};render()}
function render(){if(timer)clearInterval(timer);var q=current.questions[attempt.index];app.innerHTML=E.top(E.studentName(),"student")+E.page(current.title,"Question "+(attempt.index+1)+" of "+current.questions.length,'<div class="exam-grid"><section class="question-panel card"><div class="q-top"><span>Question '+(attempt.index+1)+' of '+current.questions.length+'</span><span>'+E.esc(q.topic||"General")+'</span></div>'+(q.image?'<div class="exam-question-image"><img src="'+q.image+'" alt="Question"></div>':"")+(q.text?'<h2>'+E.esc(q.text)+'</h2>':"")+'<div class="options">'+q.options.map(function(o,i){return '<button class="answer '+(attempt.answers[attempt.index]===i?"selected":"")+'" data-answer="'+i+'"><span class="letter">'+String.fromCharCode(65+i)+'</span><span>'+E.esc(o)+'</span></button>'}).join("")+'</div><div class="exam-actions"><button class="btn ghost" id="prev" '+(attempt.index===0?"disabled":"")+'>Previous</button><button class="btn primary" id="next">'+(attempt.index===current.questions.length-1?"Finish Exam":"Next")+'</button></div></section><aside class="question-nav card"><h3>Question Navigation</h3><div class="q-grid">'+current.questions.map(function(_,i){return '<button class="'+(attempt.answers[i]!==null?"answered ":"")+(i===attempt.index?"current":"")+'" data-q="'+i+'">'+(i+1)+"</button>"}).join("")+'</div><div class="legend"><span>● Answered</span><span>● Current</span><span>● Not answered</span></div><div class="timer"><span>◷</span> <b id="clock">'+E.fmt(attempt.left)+'</b></div><button class="btn primary full" id="finish">Finish Exam</button></aside></div>');
document.querySelectorAll("[data-answer]").forEach(function(b){b.onclick=function(){attempt.answers[attempt.index]=Number(b.dataset.answer);render()}});
document.querySelectorAll("[data-q]").forEach(function(b){b.onclick=function(){attempt.index=Number(b.dataset.q);render()}});
document.getElementById("prev").onclick=function(){if(attempt.index){attempt.index--;render()}};
document.getElementById("next").onclick=function(){attempt.index===current.questions.length-1?confirmSubmit(): (attempt.index++,render())};
document.getElementById("finish").onclick=confirmSubmit;
timer=setInterval(function(){attempt.left--;var c=document.getElementById("clock");if(c)c.textContent=E.fmt(attempt.left);if(attempt.left<=0){clearInterval(timer);submit(true)}},1000)}
function confirmSubmit(){if(confirm("Submit this exam now? Unanswered questions will be incorrect."))submit(false)}
function submit(auto){if(timer)clearInterval(timer);var score=0,total=0,correct=0,details=current.questions.map(function(q,i){var si=attempt.answers[i],ci=Number(q.correctIndex),ok=si!==null&&si===ci,p=Number(q.points||1);total+=p;if(ok){score+=p;correct++}return{questionId:q.id,selectedIndex:si,correctIndex:ci,isCorrect:ok,points:p}}),pct=total?Math.round(score/total*100):0,a={id:E.uid("attempt"),examId:current.id,examTitle:current.title,studentName:E.studentName(),startedAt:new Date(attempt.started).toISOString(),submittedAt:new Date().toISOString(),timeTaken:Math.round((Date.now()-attempt.started)/1000),score:score,totalPoints:total,percentage:pct,passed:pct>=Number(current.pass||60),correct:correct,autoSubmitted:!!auto,answers:details};S.attempts.unshift(a);localStorage.setItem("exam_local_v2_lastStudent",E.studentName());E.save();result(a)}
function result(a){current=E.exam(a.examId)||current;app.innerHTML=E.top(a.studentName,"student")+E.page(a.passed?"Congratulations!":"Exam Completed",a.passed?"You Passed":"Review your performance",'<div class="result-card card '+(a.passed?"result-pass":"result-fail")+'"><div class="result-icon">'+(a.passed?"✓":"×")+'</div><h2>'+ (a.passed?"You Passed":"You Did Not Pass")+'</h2><div class="result-score">'+a.percentage+'%</div><div class="result-stats"><div><span>Your Score</span><b>'+a.score+' / '+a.totalPoints+'</b></div><div><span>Passing Score</span><b>'+current.pass+'%</b></div></div><div class="result-meta"><span>Exam <b>'+E.esc(a.examTitle)+'</b></span><span>Correct <b>'+a.correct+' / '+current.questions.length+'</b></span><span>Time Taken <b>'+E.fmt(a.timeTaken)+'</b></span></div><div class="center"><button class="btn ghost" id="review">View Correct Answers</button><button class="btn primary" id="home">Back to Exams</button></div></div>');document.getElementById("review").onclick=function(){review(a)};document.getElementById("home").onclick=E.studentHome}
function review(a){current=E.exam(a.examId)||current;app.innerHTML=E.top(a.studentName,"student")+E.studentNav("history")+E.page("Answers Review","Your answer and the correct answer for every question.",'<div class="review-summary"><div><b>'+a.percentage+'%</b><span>Score</span></div><div><b>'+a.correct+'</b><span>Correct</span></div><div><b>'+(current.questions.length-a.correct)+'</b><span>Incorrect</span></div></div><div class="card review-list">'+rows(a)+'</div><div class="center"><button class="btn primary" id="back">Back to Results</button></div>');E.bindStudent();document.getElementById("back").onclick=function(){result(a)}}
function rows(a){return current.questions.map(function(q,i){var d=a.answers[i],sel=d.selectedIndex===null||d.selectedIndex===undefined?"Not answered":(q.options[d.selectedIndex]||""),cor=q.options[Number(q.correctIndex)]||"";return '<div class="review-row '+(d.isCorrect?"review-correct":"review-wrong")+'"><div class="review-status '+(d.isCorrect?"ok":"bad")+'">'+(d.isCorrect?"✓":"×")+'</div><div class="review-content"><b>Question '+(i+1)+'</b>'+(q.image?'<div class="review-image"><img src="'+q.image+'" alt="Question"></div>':"")+(q.text?'<p>'+E.esc(q.text)+'</p>':"")+'<div class="answer-line"><span>Your answer</span><strong class="'+(d.isCorrect?"correct-text":"wrong-text")+'">'+E.esc(sel)+'</strong></div><div class="answer-line"><span>Correct answer</span><strong class="correct-text">'+E.esc(cor)+'</strong></div></div><span class="badge '+(d.isCorrect?"pass":"fail")+'">'+(d.isCorrect?"Correct":"Incorrect")+'</span></div>'}).join("")}
E.studentHome=function(){E.stop();if(!S.user||S.user.role!=="student")return E.landing();var cards=S.exams.filter(function(e){return e.published!==false}).map(function(e){return '<article class="exam-card card"><div class="exam-icon">'+icon(e.category)+'</div><div class="exam-card-main"><span class="category">'+E.esc(e.category||"General")+'</span><h3>'+E.esc(e.title)+'</h3><p>'+E.esc(e.description||"Complete this assessment and review your answers at the end.")+'</p><div class="exam-meta"><span>'+e.questions.length+' Questions</span><span>•</span><span>'+e.duration+' Minutes</span><span>•</span><span>Pass '+e.pass+'%</span></div></div><button class="btn primary" data-start="'+e.id+'">Start</button></article>'}).join("");if(!cards)cards='<div class="card empty"><h3>No published exams</h3><p class="muted">Ask the administrator to create and publish an exam.</p></div>';app.innerHTML=E.top(E.studentName(),"student")+E.studentNav("exams")+E.page("Choose an assessment","Select an exam. Your answers stay on this device.",'<div class="exam-list">'+cards+"</div>");E.bindStudent();document.querySelectorAll("[data-start]").forEach(function(b){b.onclick=function(){E.instructions(b.dataset.start)}})}
E.instructions=function(id){current=E.exam(id);app.innerHTML=E.top(E.studentName(),"student")+E.studentNav("exams")+E.page("Exam Instructions","Review the rules before starting.",'<div class="instruction-card card"><div class="instruction-hero"><div class="big-doc">▤</div><h2>'+E.esc(current.title)+'</h2><p>'+current.questions.length+' Questions • '+current.duration+' Minutes</p></div><div class="instruction-grid"><div>◉ <b>Multiple choice</b><small>Choose one answer.</small></div><div>◷ <b>Timer</b><small>The timer cannot be paused.</small></div><div>↔ <b>Navigate freely</b><small>Review before submitting.</small></div><div>✓ <b>Correct answers</b><small>Shown immediately after submission.</small></div></div><div class="center"><button class="btn primary big-btn" id="begin">Start Exam</button><button class="btn ghost" id="back">Back to Exams</button></div></div>');document.getElementById("begin").onclick=function(){start(id)};document.getElementById("back").onclick=E.studentHome}
E.historyPage=function(){var arr=S.attempts.filter(function(a){return a.studentName===E.studentName()}),rows=arr.map(function(a){return '<tr><td>'+new Date(a.submittedAt).toLocaleDateString()+'</td><td>'+E.esc(a.examTitle)+'</td><td><b>'+a.percentage+'%</b></td><td><span class="badge '+(a.passed?"pass":"fail")+'">'+(a.passed?"Pass":"Fail")+'</span></td><td>'+E.fmt(a.timeTaken)+'</td><td><button class="mini-btn" data-review="'+a.id+'">Answers</button></td></tr>'}).join("");app.innerHTML=E.top(E.studentName(),"student")+E.studentNav("history")+E.page("My Exam History","Completed exams stored locally.",'<div class="table-wrap card"><table class="table"><thead><tr><th>Date</th><th>Exam</th><th>Score</th><th>Result</th><th>Time</th><th>Review</th></tr></thead><tbody>'+(rows||'<tr><td colspan="6" class="muted">No exams yet.</td></tr>')+'</tbody></table></div>');E.bindStudent();document.querySelectorAll("[data-review]").forEach(function(b){b.onclick=function(){review(E.att(b.dataset.review))}})}
E.profilePage=function(){var arr=S.attempts.filter(function(a){return a.studentName===E.studentName()}),avg=arr.length?Math.round(arr.reduce(function(s,a){return s+a.percentage},0)/arr.length):0;app.innerHTML=E.top(E.studentName(),"student")+E.studentNav("profile")+E.page("My Profile","Student information and local performance.",'<div class="profile-card card"><div class="avatar">'+E.esc(E.studentName().charAt(0).toUpperCase())+'</div><h2>'+E.esc(E.studentName())+'</h2><p class="muted">Student</p><div class="profile-stats"><div><b>'+arr.length+'</b><span>Attempts</span></div><div><b>'+avg+'%</b><span>Average</span></div></div><div class="center"><button class="btn ghost" id="switch">Switch Student</button><button class="btn primary" id="admin">Admin Panel</button></div></div>');E.bindStudent();document.getElementById("switch").onclick=function(){S.user=null;localStorage.removeItem("exam_local_v2_session");E.landing()};document.getElementById("admin").onclick=E.adminLogin}
})();